config/routes.rb
Rails.application.routes.draw do

  root 'lists#home'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'log_out'
  delete '/logout', to: 'sessions#destroy'

  get '/about', to: 'lists#about', as: 'about'
  get '/', to: 'lists#home', as: 'home'

  resources :users
  resources :lists do
    resources :tasks
  end

end

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :list
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates(:email, presence: true)

	has_many :lists

	has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	def index
		@lists = List.where(user_id: session[:user_id])
	end

	def show
		@list = List.find(params[:id])

	end

	def new
		@list = List.new
	end

	def create
		@list = User.find(session[:user_id]).lists.build(list_params)
		if @list.save
			redirect_to lists_path
		else
			@errors = "Please create a proper list"
			render 'new'
		end
	end

	def edit
		@list = List.find(params[:id])
	end

	def update
		@list = List.find(params[:id])
		@list.update(list_params)
		redirect_to lists_path
	end

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		redirect_to lists_path
	end

	def about

	end

	def home

	end

	private
	def list_params
		params.require(:list).permit(:name)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by(:username => session_params[:username]).try(:authenticate, session_params[:password])

		if @user
			session[:user_id] = @user.id
			redirect_to lists_path
		else
			@error = "Incorrect username, email, or password"
			render 'sessions/new'
		end

	end

	def destroy
		session.destroy
		redirect_to root_path
	end

	private

	def session_params
		params.require(:session).permit(:username, :email, :password)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def new
		@list = List.find(params[:list_id])

	end


	def create
		@list = List.find(params[:list_id])

		if session[:user_id]
			@task = @list.tasks.create(task_params)
			#binding.pry
			# puts '-'*20
			# puts comment_params
			# puts '-'*20
			redirect_to list_path(@list)
		else
			flash[:notice] = "You need to be logged in to create tasks"
			redirect_to list_path(@list)
  	end
	end



	def edit
		@list = List.find(params[:list_id])
		@task = @list.tasks.find(params[:id])
	end

	def update
		@list = List.find(params[:list_id])
		@task = @list.tasks.find(params[:id])
		@task.update(task_params)
		redirect_to list_path(@list)
	end

	def destroy
		@list = List.find(params[:list_id])
		@task = @list.tasks.find(params[:id])
		@task.destroy
		redirect_to list_path(@list)
	end

	# marking tasks as complete
	def complete
		@list = List.find(params[:list_id])
		@task = @list.tasks.find(params[:id])



		redirect_to lists_path(@list)
	end


	private
	def task_params
		params.require(:task).permit(:task, :due_date, :completed)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to lists_path(@user)
		else
			@error = "Please enter all fields to create an account"
			render 'new'
		end
	end

	def edit
		@user = User.find(session[:user_id])
	end

	def update
		@user = User.find(session[:user_id])
		@user.update
		redirect_to lists_path
	end

	def destroy
		@user.destroy
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		User.find(session[:user_id]) if session[:user_id]
	end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<p id="footer">Copyright 2015 TList </br></br>
<%= link_to 'About us',about_path%>   <%= link_to 'Privacy Policy',about_path%>   <%= link_to 'Terms/Conditions',about_path%>   <%= link_to 'Community',about_path%></p>
</br>

app/views/layouts/_header.html.erb
<h1 id="brand"><%= link_to 'TaskLIST', root_path, class: 'text-color:white;' %></h1>

<% if current_user %>
	<ul id="nav">
		<li><%= link_to "Logout", log_out_path %></li>
		<li><%= link_to "New List", new_list_path %></li>
		<li><%= link_to "My Lists", lists_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Home", home_path %></li>


	</ul>
<% else %>
	<ul id="nav">
		<li><%= link_to "Login", login_path %></li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Home", home_path %></li>
		

	</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrap">
		<%= render 'layouts/header' %>
			<div id="content">
				<%= yield %>
			</div>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/lists/_form.html.erb
<div class="form">	

	<%= form_for(@list) do |f| %>
		<p>Name:</p>
		<%= f.text_field :name %>
		<%= f.submit "Save List" %>
	<% end %>

</div>

app/views/lists/_tasks.html.erb
<strong><p>-------------------</p></strong>
		
<strong><h4>Task:</h4></strong>
<strong><p><%= task.task %></p></strong>
<p>Due Date:</p>
<p><%= task.due_date %></p>

<%= form_for([@list,task]) do |t| %>
	<p>Completed?</p>
	<%= t.check_box :completed %>
	<%= t.submit "Save" %>
<% end %>

<p>----------</p>

<%= link_to edit_list_task_path(@list,task), remote: true do %>
	<button class="btn btn-default">Edit</button>
<% end %>

<%= link_to 'Delete', [@list,task], method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/lists/about.html.erb
<h2 style="text-align:center;">About this site</h2>
<p style="text-align:center;">This is a site where users can create tasklists and add tasks to them. They can choose whether to check tasks as completed or still pending.</p>

app/views/lists/edit.html.erb
<h2>Edit Listing</h2>

<%= render 'form' %>

app/views/lists/home.html.erb
<h2 style='text-align:center;'>Welcome to TList!</h2>
<h4 style='text-align:center;'>The site that helps you stay organized throughout your life.</h4>
</br>
<h3 style='text-align:center'>Please <%= link_to 'Login', login_path %> or <%= link_to 'Sign Up', new_user_path %></h3>

app/views/lists/index.html.erb
<div class="lists-index">
	<h2>My Lists</h2>

	<% @lists.each do |list| %>
		<p><%= link_to list.name, list_path(list) %>
		<%= link_to 'Edit', edit_list_path(list) %>
		<%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	<% end %>
</div>

app/views/lists/new.html.erb
<p><%= @error %></p>

<h2>New List</h2>

<%= render 'form' %>

app/views/lists/show.html.erb
<strong><h1><%= @list.name %></h1></strong>

<div class="task-java">
	<%= flash[:notice] %>

	<h2>New Task for <%= @list.name %></h2>

	<%= link_to new_list_task_path(@list), remote: true do %>
	  <button class="btn btn-default">New</button>
	<% end %>
	<div class="row">
	  <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
	</div>

	<div class="row">
	  <div id="task-form-each" style="display:none;"></div>
	</div>
</div>




<h2>CURRENT TASKS</h2>

<% @list.tasks.each do |task| %>

	<% if task.completed == false %>
	
		<div class="task-show">
			<strong><h1>-------------------------------------------</h1></strong>
			<strong><p>Task:</p></strong>
			<p><%= task.task %></p>
			<strong><p>Due Date:</p></strong>
			<p><%= task.due_date %></p>
			<strong><p>Completed:</p></strong>
			<p>
				<%= form_for([@list,task]) do |t| %>
					<%= t.check_box :completed %>
					<%= t.submit "Save" %>
				<% end %>
			</p>

			<p>------------------</p>

			<p><%= link_to edit_list_task_path(@list,task), remote: true do %>
						<button class="btn btn-default">Edit</button>
					<% end %></p>
			<p><%= link_to 'Delete', [@list,task], method: :delete, data: { confirm: 'Are you sure?' } %>
			</p>
			<strong><h1>-------------------------------------------</h1></strong>
		</div>


	<% end %>
<% end %>


<h2>COMPLETED TASKS</h2>
<% @list.tasks.each do |task| %>


	<% if task.completed == true %>

		<div class="task-show">

			<strong><h1>-------------------------------------------</h1></strong>
			<strong><p>Task:</p></strong>
			<p><%= task.task %></p>
			<strong><p>Due Date:</p></strong>
			<p><%= task.due_date %></p>
			<strong><p>Completed:</p></strong>
			<p><%= form_for([@list,task]) do |t| %>
						<%= t.check_box :completed %>
						<%= t.submit "Save" %>
					<% end %>
			</p>

			<p>------------------</p>

			<p><%= link_to edit_list_task_path(@list,task), remote: true do %>
						<button class="btn btn-default">Edit</button>
					<% end %></p>
			<p><%= link_to 'Delete', [@list,task], method: :delete, data: { confirm: 'Are you sure?' } %>
			</p>

		</div>

	<% end %>
<% end %>

app/views/tasks/_form.html.erb
<div class="form">	
	<%= form_for([@list, @list.tasks.build]) do |t| %>

		<strong><p>Task:</p></strong>
		<p><%= t.text_field :task %></p>
		<strong><p>Due Date:</p></strong>
		<p><%= t.text_field :due_date %></p>
		<p><%= t.submit 'Save' %></p>

	<% end %>
<div>	

app/views/tasks/_formEdit.html.erb
<div class="form">	
	<%= form_for([@list,@task]) do |t| %>
		
		<strong><p>Task:</p></strong>
		<p><%= t.text_field :task %></p>
		<strong><p>Due Date:</p></strong>
		<p><%= t.text_field :due_date %></p>
		<strong><p>Completed</p></strong>
		<p><%= t.check_box :completed %></p>
		<p><%= t.submit 'Save' %></p>
		
	<% end %>
</div>

app/views/tasks/create.js.erb
$('#task-form').slideUp(350);

app/views/tasks/edit.js.erb
$('#task-form-each').html("<%= j (render 'formEdit') %>");
$('#task-form-each').slideDown(350);

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/update.js.erb
$('#task-form-each').slideUp(350);

app/views/users/new.html.erb
<div class="signup">	
	<h2>Sign Up</h2>
	<p><%= @error %></p>
	<%= form_for(@user) do |f| %>
		<p>Username:</p>
		<p><%= f.text_field :username %></p>
		<p>Email</p>
		<p><%= f.text_field :email %></p>
		<p>Password</p>
		<p><%= f.password_field :password %></p>
		<p>Password Confirmation</p>
		<p><%= f.password_field :password_confirmation %></p>
		<p><%= f.submit 'Sign Up' %></p>
	<% end %>

	<p>Already a member?</p>
	<%= link_to 'Login to Account', login_path %>
</div>